model_name: o3
model_type: openai_api_models
base_model_name: o3

# No use for gpt models
model_max_length: 131072

# only used for making savefile directory
model_name_summary: o3/o3

# tokenizer name, used for tokenizer_separator
tokenizer_name: o3

# used for saving files
save_file_name: o3

finetuned_tokenizer: False