COMBO_BELIEF_GENERATION_FAILURE_MSG="Belief generation failed to parse. The belief must be contained within <belief> ... </belief> tags. Try again."
    
COMBO_NO_PRIOR_BELIEF_MESSAGE="No prior belief."

COMBO_INVALID_ACTION_MESSAGE="invalid action"

COMBO_AGENT_FIRST_MESSAGE="""You will determine the correct combination of characters at [Position 1, Position 2, Position 3] in a 3-character combination lock through iterative reasoning and queries.
All 3 characters are unique.
The set of valid characters are as follows: {vocab_list}
Each action is a query of the form ['char 1', 'char 2', 'char 3'].
Each time you query a combination, you will get feedback from the user about each character: either not in the combination, in the combination but in a different position, or in the combination and in the right position.
You can make up to {max_attempts} queries.
Your goal is to find the correct combination in the least number of queries."""

COMBO_FIRST_USER_MESSAGE="""Give me your first query formatted as a list of 3 characters inside <action> ... </action> after thinking inside <think> ... </think>, e.g., <think> Let's think step by step before giving the query [your extensive thinking] </think> <action>['char 1', 'char 2', 'char 3']</action>.
""" 
# interesting to note that the new line is here and was on the two below, before the most recent runs. This is just a sanity check

COMBO_BELIEF_PROMPT="""{agent_first_message}
Your current belief state: <belief>{belief_state}</belief>
Your last action:
<action>{agent_action}</action>
Environment feedback:
{env_response}
Now update your belief state to include all important new information you have gathered.
Do not say anything about future actions. Think step by step and then output your new belief state inside <belief> ... </belief>, e.g., <think>Any thinking</think><belief>your new beliefs</belief>."""

COMBO_BELIEF_PROMPT_SINGLE_CONTEXT = """Now update your belief state to include all important new information you have gathered.
Do not say anything about future actions. Think step by step and then output your new belief state inside <belief> ... </belief>, e.g., <think>Any thinking</think><belief>your new beliefs</belief>."""
COMBO_ACTION_PROMPT_SINGLE_CONTEXT = """Now think step by step and then output your next action formatted as a list of 3 characters inside <action> ... </action>, e.g.,<think>Any step by step, short and concise thinking to determine your next action</think><action>['char 1', 'char 2', 'char 3']</action>."""
COMBO_ACTION_PROMPT="""Global Instruction: {agent_first_message}
Current belief: <belief>{belief_state}</belief>
Now think step by step and then output your next action formatted as a list of 3 characters inside <action> ... </action>, e.g.,<think>Any step by step, short and concise thinking to determine your next action</think><action>['char 1', 'char 2', 'char 3']</action>."""


COMBO_BELIEF_GRADING_PROMPT = """Your job is to parse belief states generated by another langauge model while its being trained.
The other langauge model is playing a combination lock game. Here are the rules to that game:
```
You will determine the correct combination of characters at [Position 1, Position 2, Position 3] in a 3-character combination lock through iterative reasoning and queries.
All 3 characters are unique.
The set of valid characters are as follows: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
Each action is a query of the form ['char 1', 'char 2', 'char 3'].
Each time you query a combination, you will get feedback from the user about each character: either not in the combination, in the combination but in a different position, or in the combination and in the right position.
You can make up to 12 queries.
Your goal is to find the correct combination in the least number of queries.
```
The problem is I can only parse a very simple format:
```
possible characters in position 1: []
possible characters in position 2: []
possible characters in position 3: []
```
Here are some examples
if you see:
```
Position 2 is '1'. Possible characters for Position 1 and Position 3 are ['3', '4', '5', '6', '7', '8', '9']. These characters must be unique.
```
You should return:
```
possible characters in position 1: [3, 4, 5, 6, 7, 8, 9]
possible characters in position 2: [1]
possible characters in position 3: [3, 4, 5, 6, 7, 8, 9]
```
if you see:
```
The characters '0', '1', and '2' are not in the combination. The possible characters for the combination are ['3', '4', '5', '6', '7', '8', '9']. Each of the 3 characters in the combination must be unique.
```
You should return:
```
possible characters in position 1: [3, 4, 5, 6, 7, 8, 9]
possible characters in position 2: [3, 4, 5, 6, 7, 8, 9]
possible characters in position 3: [3, 4, 5, 6, 7, 8, 9]
```
if you see:
```
The lock combination is one of the following: ['2', '5', '7'], ['2', '5', '8'], ['2', '5', '9'], ['2', '7', '8'], ['2', '7', '9'], ['2', '8', '9']. The character '5' is in the second position. We need to determine the correct characters for the first and third positions.
```
You should return:
```
possible characters in position 1: [2, 7, 8, 9]
possible characters in position 2: [5]
possible characters in position 3: [2, 7, 8, 9]
```
if you see:
```
The third character is '5'. The possible characters for the first and second positions are ['3', '6', '7', '8', '9']. The first and second characters must be unique and not '5'.
```
You should return:
```
possible characters in position 1: [3, 6, 7, 8, 9]
possible characters in position 2: [3, 6, 7, 8, 9]
possible characters in position 3: [5]
```
if you see:
```
- 2 is in the lock and in Position 2.
- Possible positions for 2: Position 2.
- Remaining valid characters for Position 1 and Position 3: ['4', '5', '6', '7', '8'].
- 3 and 9 are not in the lock.
```
You should return:
```
possible characters in position 1: [4, 5, 6, 7, 8]
possible characters in position 2: [2]
possible characters in position 3: [4, 5, 6, 7, 8]
```
Please parse the following
```
{belief}
```"""
COMBO_BELIEF_GRADING_PROMPT_FILLER_BELIEF = """- 2 is in the lock and in Position 2.
- Possible positions for 2: Position 2.
- Remaining valid characters for Position 1 and Position 3: ['4', '5', '6', '7', '8'].
- 3 and 9 are not in the lock."""

# possible characters in position 1: [3, 4, 5, 6, 7, 8, 9]\npossible characters in position 2: [1]\npossible characters in position 3: [3, 4, 5, 6, 7, 8, 9]