tools:
  - class_name: "verl.tools.combo_lock_tool.ComboLockTool"
    config: {}
    tool_schema:
      type: "function"
      function:
        name: "test_combination"
        description: "See how close the combination is to the true one."
        strict: true
        parameters:
          type: "object"
          required:
            - "digit1"
            - "digit2"
            - "digit3"
          properties:
            digit1:
              type: "number"
              minimum: 0
              exclusiveMaximum: 10
              description: "The first digit of the combination lock"
            digit2:
              type: "number"
              minimum: 0
              exclusiveMaximum: 10
              description: "The second digit of the combination lock"
            digit3:
              type: "number"
              minimum: 0
              exclusiveMaximum: 10
              description: "The third digit of the combination lock"
          additionalProperties: false

